######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 14 17:16:17 2014
######################################################################

TEMPLATE = app
TARGET = viewmap

CONFIG += c++11
QMAKE_CXXFLAGS += -std=c++11
QT += widgets

SOURCES += \
    main.cpp \
    scaler.cpp \
    view.cpp \
    graphicstree.cpp \
    graphicsfood.cpp

HEADERS += \
    scaler.h \
    view.h \
    graphicstree.h \
    graphicsfood.h
